#!/bin/bash

echo -e "Installing application..."

cf p apmServices -p ~/Repos/gradProject/APMServices/target/APMServices-1.0-SNAPSHOT.war

cf set-env apmServices staticAppUrl 'https://staticapp-hirable-phrasing.cfapps.io'

cf set-env apmServices targetUrl 'https://api.run.pivotal.io'

cf restage apmServices
