#!/bin/bash

echo -e "Installing apm plugin..."

rm ~/Repos/gradProject/goCode/bin/main

go build ~/Repos/gradProject/goCode/src/main.go

mv ~/Repos/gradProject/main ~/Repos/gradProject/goCode/bin/

cf uninstall-plugin apmPlugin

cf install-plugin ~/Repos/gradProject/goCode/bin/main
