#!/bin/bash

echo -e "Installing apm plugin..."

rm ~/Repos/gradProject/plugin/bin/main

go build ~/Repos/gradProject/plugin/src/main.go

mv ~/Repos/gradProject/main ~/Repos/gradProject/plugin/bin/

cf uninstall-plugin apmPlugin

cf install-plugin ~/Repos/gradProject/plugin/bin/main
