#!/bin/bash

echo -e "Installing application..."

cf p apmServices -p ./APMServices/target/APMServices-1.0-SNAPSHOT.war --no-start

cf set-env apmServices staticAppUrl 'https://staticapp-hirable-phrasing.cfapps.io'

cf set-env apmServices targetUrl 'https://api.run.pivotal.io'

cf set-env apmServices github 'https://raw.githubusercontent.com/radito3/gradProject/github_dwnl/packages'

cf start apmServices
